# Define the version of the Compose file format
version: '3.8'

services:
  # Define the Flask application service
  flask_app:
    # Build the Docker image from the current directory
    build: .
    # Mount the app, logs, and data directories from the host to the container
    volumes:
      - ./app:/app
      - ./logs:/logs
      - ./data:/data
    # Set environment variables for the Flask app
    environment:
      - FLASK_ENV=development

  # Define the web server service (Nginx)
  web_server:
    # Build the Docker image from the current directory using the specified Dockerfile
    build:
      context: .
      dockerfile: Dockerfile.nginx
    # Map port 80 on the host to port 80 on the container
    ports:
      - "80:80"
    # Ensure the web server starts after the Flask app
    depends_on:
      - flask_app
    # Mount the logs directory from the host to the container
    volumes:
      - ./logs:/logs
